widgetTheme=widget-themes/original
primaryColor=#36a9e1
secondaryColor=#86C953
labelColor=#ffffff
hideWhenOffline=false
contactMail=miguel.angel@innovadsl.es
loadingLabel=Cargando...
loginError=Error de acceso
chatHeader=Especialista Online Disponible
startInfo=Por favor, rellena el siguiente formulario para empezar
widgetWidth=370
widgetHeight=411
widgetOffset=50
mobileBreakpoint=550
maxConnections=5
messageSound=audio/default.mp3
startLabel=Empezar
backLabel=Atras
initMessageBody=Hola, en qué podemos ayudarte
initMessageAuthor=Operador
chatInputLabel=Escribe tu pregunta
timeDaysAgo=day(s) ago
timeHoursAgo=hour(s) ago
timeMinutesAgo=minute(s) ago
timeSecondsAgo=second(s) ago
offlineMessage=El operador se desconectó
toggleSoundLabel=Efectos de sonido
toggleScrollLabel=Auto-scroll
toggleEmoticonsLabel=Emoticonos
toggleAutoShowLabel=Auto-show
toggleFullscreenLabel=Pantalla completa
endChatLabel=Acabar chat
endChatConfirmQuestion=Estás seguro?
endChatConfirm=Si
endChatCancel=Cancelar
contactHeader=Contacta con nosotros
contactInfo=Todos los operadores están desconectados. Usa el formulario de abajo para mandarnos un email con tu pregunta.
contactNameLabel=Tu nombre
contactMailLabel=Tu email
contactQuestionLabel=Tu pregunta
contactSendLabel=Enviar
contactSuccessHeader=Mensaje enviado
contactSuccessMessage=Tu pregunta ha sido enviada. Gracias!
contactErrorHeader=Error
contactErrorMessage=Ha habido un error enviando tu mensaje.
headerHeight=55
installed=1
autoShowWidgetAfter=10
autoShowWidget=true
